Repository kptm-tools/web-ui, pull requests merged in 2025-03, with the labels that each got.

#23 feat(DialogReportInsight): Add time_period.vulnerability_count object null check
  src/components/Dialog/DialogReportInsight.vue
Labels: bug, enhancement

#25 Feature/kt 397 add verifyemailpage
  src/components/Dialog/DialogReportInsight.vue
  src/pages/auth/VerifyEmailPage.vue
  src/router/routes-names.ts
  src/router/routes.ts
  src/services/user.service.ts
  src/utils/notify.utils.ts
Labels: enhancement

#26 Feature/kt 390 add vendor comment component
  src/components/report/VulnerabilityCard.vue
  src/models/scans.model.ts
Labels: enhancement

#24 Add scan schedule
  src/components/Dialog/DialogScan.vue
  src/components/Table/TableScan.vue
  src/components/scan/ScanScheduleStep.vue
  src/models/hosts.models.ts
  src/models/scans.model.ts
  src/services/scan.service.ts
  src/utils/scan.utils.ts
  yarn.lock
Labels: enhancement

#27 Feature/kt 372 comment functionality
  src/components/report/VulnerabilityCard.vue
  src/pages/ReportDetailPage.vue
  src/pages/ReportDetailVulnerability.vue
  src/services/vulnerabilites.service.ts
Labels: enhancement

#30 fix(heatmap): Update heatmap legend apex color constants
  src/constants/apexcharts.constants.ts
Labels: bug

#33 Kt 404 fe dashboard typos design
  src/models/dashboard.models.ts
  src/pages/IndexPage.vue
  src/services/dashboard.ts
Labels: bug, enhancement
