Repository kptm-tools/web-ui, pull requests merged in 2025-08, with the labels that each got.

#85 feat: Add back navigation and improve interface visuals [VUL-4]
  src/modules/vulnerability/pages/ReportDetailPage.vue
Labels: help wanted

#91 fix: unclutter dashboards and insights [VUL-9]
  src/constants/apexcharts.constants.ts
  src/modules/vulnerability/VulnerabilityModule.vue
  src/modules/vulnerability/components/chart/LatestScanChart.vue
  src/modules/vulnerability/components/chart/OverallSecurityPostureChart.vue
  src/modules/vulnerability/components/chart/VulnerabilityTrendChart.vue
  src/modules/vulnerability/components/dialog/DialogScanInsight.vue
  src/modules/vulnerability/components/list/HostMostVulnerabilitiesList.vue
  src/modules/vulnerability/models/dashboard.ts
  src/modules/vulnerability/pages/IndexPage.vue
  src/modules/vulnerability/services/dashboard.ts
Labels: enhancement

#93 Aud 142
  src/modules/shared/routes/routes.ts
Labels: help wanted

#96 feat(ReportServiceCard): Add placeholder when OS is not detected [VUL-18]
  src/modules/vulnerability/components/card/ReportServiceCard.vue
Labels: enhancement, help wanted
